# Generated by Django 4.0.1 on 2022-04-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('centers', models.CharField(max_length=120)),
                ('slots', models.PositiveIntegerField()),
            ],
        ),
    ]
